name: Run deployment on release branches

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Docker login
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        - name: Build and push Docker image
          run: |
            if [ "${{ github.ref_name }}" == "dev" ]; then
              docker build -t ${{ secrets.DOCKER_REPONAME}}:${{ github.ref_name }}-${{ github.sha }} .
              docker push ${{ secrets.DOCKER_REPONAME}}:${{ github.ref_name }}-${{ github.sha }}
            fi
            if [ "${{ github.event_name }} == "release" ]; then
              docker build -t ${{ secrets.DOCKER_REPONAME}}:prod-${{ github.ref_name }} .
              docker push ${{ secrets.DOCKER_REPONAME}}:prod-${{ github.ref_name }}
            fi
        